const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  toggleLock: (locked) => ipcRenderer.send('toggle-lock', locked),
  setWindowIdleOpacity: (percentual) => ipcRenderer.send('set-window-idle-opacity', percentual),
  setWindowPointerIdle: (idle) => ipcRenderer.send('set-window-pointer-idle', idle),
  closeApp: () => ipcRenderer.send('close-app'),
  expandWindow: () => ipcRenderer.send('expand-window'),
  collapseWindow: () => ipcRenderer.send('collapse-window'),
  cancelHide: () => ipcRenderer.send('cancel-hide'),
  setConsoleEnabled: (enabled) => ipcRenderer.invoke('set-console-enabled', enabled),
  onWindowState: (callback) => ipcRenderer.on('window-state', callback),
  openObsWindow: () => ipcRenderer.send('open-obs-window'),
  closeObsWindow: (content) => ipcRenderer.send('close-obs-window', content),
  onObsContentUpdated: (callback) => ipcRenderer.on('obs-content-updated', callback),
  buscarPedido: (numeroPedido) => ipcRenderer.invoke('buscar-pedido', numeroPedido),
  salvarPedido: (pedidoData) => ipcRenderer.invoke('salvar-pedido', pedidoData),
  buscarPorCPF: (cpf) => ipcRenderer.invoke('buscar-por-cpf', cpf),
  buscarCertificados: () => ipcRenderer.invoke('buscar-certificados'),
  salvarCertificado: (certificado) => ipcRenderer.invoke('salvar-certificado', certificado),
  excluirCertificado: (nome) => ipcRenderer.invoke('excluir-certificado', nome),
  buscarConfiguracoes: (usuario) => ipcRenderer.invoke('buscar-configuracoes', usuario),
  salvarConfiguracoes: (config) => ipcRenderer.invoke('salvar-configuracoes', config),
  getCredentials: () => ipcRenderer.invoke('get-credentials'),
  authLogout: () => ipcRenderer.invoke('auth-logout'),
  authRecuperarSenha: (email) => ipcRenderer.invoke('auth-recuperar-senha', { email }),
  authConfirmarRecuperacao: (data) => ipcRenderer.invoke('auth-confirmar-recuperacao', data),
  buscarPedidos: (filtros) => ipcRenderer.invoke('buscar-pedidos', filtros),
  exportarPedidosExcel: (payload) => ipcRenderer.invoke('exportar-pedidos-excel', payload),
  contarStatusPedidos: () => ipcRenderer.invoke('contar-status-pedidos'),
  getCurrentUser: () => ipcRenderer.invoke('get-current-user'),
  verificarPastaPedido: (data) => ipcRenderer.invoke('verificar-pasta-pedido', data),
  criarPastaPedido: (data) => ipcRenderer.invoke('criar-pasta-pedido', data),
  abrirPastaPedido: (data) => ipcRenderer.invoke('abrir-pasta-pedido', data),
  obterPastaPedido: (data) => ipcRenderer.invoke('obter-pasta-pedido', data),
  obterPastaUsuario: (data) => ipcRenderer.invoke('obter-pasta-usuario', data),
  abrirPastaUsuario: (data) => ipcRenderer.invoke('abrir-pasta-usuario', data),
  salvarAnexoPedido: (data) => ipcRenderer.invoke('salvar-anexo-pedido', data),
  salvarAnexoPedidoComConteudo: (data) => ipcRenderer.invoke('salvar-anexo-pedido-conteudo', data),
  capturarPrintPedido: (data) => ipcRenderer.invoke('capturar-print-pedido', data),
  listarAnexosPedido: (data) => ipcRenderer.invoke('listar-anexos-pedido', data),
  abrirArquivo: (filePath) => ipcRenderer.invoke('abrir-arquivo', filePath),
  abrirLinkExterno: (url) => ipcRenderer.invoke('abrir-link-externo', url),
  // Cadastro de usuarios: exige sessao ativa (checado no processo principal)
  criarUsuario: (dados) => ipcRenderer.invoke('auth-register', dados),
  excluirPastaPedido: (data) => ipcRenderer.invoke('excluir-pasta-pedido', data),
  excluirAnexoPedido: (data) => ipcRenderer.invoke('excluir-anexo-pedido', data),
  getPathForFile: (file) => webUtils?.getPathForFile ? webUtils.getPathForFile(file) : file?.path,
  // Atualizacao silenciosa: a interface so escuta o estado; nao ha nada para
  // iniciar ou cancelar, o download roda sozinho e a instalacao acontece ao sair.
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (event, payload) => callback(payload))
});
